services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=legendary_winner
    volumes:
      - .:/app # Mount your local code into the container
      - /app/node_modules # Prevent overwriting node_modules in the container
    working_dir: /app
    depends_on:
      - database
    command: npm run start:dev
    restart: always

  database:
    image: postgres:14
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: legendary_winner
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
