version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=legendary_winner
    depends_on:
      - database

  database:
    image: postgres:14
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: legendary_winner
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
